qcplay/qcplay/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from stark.service.v1 import site
from web.views import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 路由系统
    url(r'^stark/', site.urls),
    # 权限系统
    url(r'^rbac/', include(('rbac.urls', 'rbac'), namespace='rbac')),


    url(r'^select2/', include("django_select2.urls")),

    # 用户
    #url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/', views.LooutView.as_view(), name='logout'),
    url(r'^index/', views.IndexView.as_view(), name='index'),

]

qcplay/apps/stark/models.py
from django.db import models

# Create your models here.

qcplay/apps/web/models.py
import hashlib


from django.contrib.auth.hashers import make_password
from django.db import models
from datetime import datetime
from rbac.models import UserInfo as RbacUserInfo


class UserInfo(RbacUserInfo):  # 继承rbac的UserInfo基类
    """
    用户表
    """
    nickname = models.CharField(verbose_name='真实姓名', max_length=16)
    phone = models.CharField(verbose_name='手机号', max_length=32)

    gender_choices = ((1, '男'), (2, '女'))
    gender = models.IntegerField(verbose_name='性别', choices=gender_choices, default=1)
    #depart = models.ForeignKey(verbose_name='部门', to='Department', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        #self.password = hashlib.sha1(self.password.encode("utf-8")).hexdigest()
        self.password = make_password(self.password, salt='qc', hasher ='pbkdf2_sha1')
        super(UserInfo, self).save(*args, **kwargs)

    def __str__(self):
        return self.nickname


class IdcHost(models.Model):
    """
    主机表
    """
    title = models.CharField(verbose_name='主机名', max_length=32,unique=True)
    system = models.CharField(verbose_name='系统', max_length=32,null=True, blank=True)
    outernet_ip = models.CharField(verbose_name='外网ip', max_length=32)
    intranet_ip = models.CharField(verbose_name='内网ip', max_length=32)
    cpu = models.CharField(verbose_name='CPU', max_length=32,null=True, blank=True)
    memory = models.CharField(verbose_name='内存', max_length=32,null=True, blank=True)
    disk = models.CharField(verbose_name='硬盘', max_length=32,null=True, blank=True)
    username = models.CharField(verbose_name='用户', max_length=32,null=True, blank=True)
    password = models.CharField(verbose_name='密码', max_length=32,null=True, blank=True)
    port = models.CharField(verbose_name='端口', max_length=32,null=True, blank=True)
    ssh_port = models.CharField(verbose_name='ssh端口', max_length=32,null=True, blank=True)
    status_choices = ((1, '启用'), (2, '禁用'))
    status = models.IntegerField(verbose_name='当前状态', choices=status_choices, default=1)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间", null=True, blank=True)

    def __str__(self):
        return self.title
    def get_outernet_ip(self):
        if self.outernet_ip:
            return self.outernet_ip

class Repo(models.Model):
    type_choices = (
        ('git', u'git'),
        ('svn',u'svn'),
    )
    title = models.CharField(verbose_name='版本库名', max_length=32, unique=True)
    rtype = models.CharField(choices=type_choices, verbose_name='更新类型', max_length=10)
    addr = models.CharField(verbose_name='仓库地址', max_length=100)
    repoUser = models.CharField(max_length=50, verbose_name='用户', null=True, blank=True)
    repoPassword = models.CharField(max_length=50, verbose_name='密码', null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.addr


class SiteDir(models.Model):
    title = models.CharField(verbose_name='名称', max_length=32, unique=True)
    path = models.CharField(verbose_name='路径', max_length=32, unique=True)

    def __str__(self):
        return self.title

class WebSite(models.Model):
    type_choices = (
        ('git', u'git'),
        ('svn',u'svn'),
    )
    title = models.CharField(verbose_name='站点名称', max_length=32,unique=True)
    desc = models.CharField(verbose_name='站点描述', max_length=32, null=True, blank=True)
    target = models.ForeignKey(to='IdcHost',verbose_name='主机', on_delete=models.CASCADE)
    sitedir = models.ForeignKey(to='SiteDir',verbose_name='站点目录', on_delete=models.CASCADE)
    wtype = models.CharField(choices=type_choices, verbose_name='更新类型', max_length=10)
    addr = models.ForeignKey(Repo, on_delete=models.CASCADE, verbose_name='仓库地址')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.title

qcplay/apps/stark/forms/widgets.py
# by 362416272@qq.com
from django import forms


class DateTimePickerInput(forms.TextInput):
    template_name = 'stark/forms/widgets/datetime_picker.html'

qcplay/apps/stark/templates/stark/change.html
{% extends 'layout.html' %}
{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />
<style>


</style>
{% endblock %}

{% block content %}
<div class="layui-row">
    <div class="layui-col-md6">
        <div class="layui-card" style="margin: 20px">
            <div class="layui-card-header">新增数据</div>
            <div class="layui-card-body">
                <form class="layui-form" method="post" id="changeForm" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="layui-form-item">
                        <label class="layui-form-label">{{ field.label }}
                            <div class="layui-form-mid layui-word-aux" style="float: left"></div>
                        </label>
                        <div class="layui-input-block">
                            {{ field }}
                        </div>
                        <span style="color: red">{{ field.errors.0 }}</span>
                    </div>
                    {% endfor %}

                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button class="layui-btn" lay-submit lay-filter="formDemo" style="width: 190px">保存</button>
                            <!--<input type="button" class="layui-btn" lay-submit lay-filter="formDemo" style="width: 190px" value="保存" onclick="formcheck();" />-->
                        </div>
                    </div>
                </form>
                <!--{% if messages %}-->
                <!--{% for message in messages %}-->
                <!--<input id="id_msgs" type="hidden" tags="{{message.tags}}" value="{{ message }}">-->
                <!--{% endfor %}-->
                <!--{% endif %}-->
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>
<script>

    layui.use('form', function () {
        var form = layui.form;
        var layer = layui.layer;
        function init_input(){
            $("#id_repoUser").parent().parent().css("display","none");
            $("#id_repoPassword").parent().parent().css("display","none");
        }

        if ($('#id_rtype').val() != 'svn'){
                init_input()
        }
        //$("#id_addr").select2({placeholder: 'Select an option'});
        //$("#id_addr").djangoSelect2();
        form.on('select(f_wtype)', function(data){
             $.ajax({
                 type: "POST",
                 url: "/stark/web/website/get_repo/",
                 data: {"type":data.value,"csrfmiddlewaretoken":"{{ csrf_token }}"},
                 dataType: "json",
                 success: function(res){
                            $("#id_addr").html('')
                            var optionEle = "<option value=''>直接选择或搜索选择</option>";
                            data = jQuery.parseJSON(res.data)
                            for(var i = 0;i < data.length;i++){
                                optionEle += "<option value='"+data[i].pk+"'>"+data[i].fields.addr+"</option>";
                            }
                            //原本想使用select2插件
                            //$("#id_addr").append(optionEle).trigger('change.select2');
                            //$("#id_addr").append(optionEle).find('select').select2();
                            //$("#id_addr").select2("open");
                            //$("#id_addr").append(optionEle).trigger('change.select2');
                            //$("#id_addr").select2();
                            //后来直接使用layui自带的功能
                            $("#id_addr").append(optionEle);
                            form.render();
                          }
             });
        });

        form.on('select(f_rtype)', function(data){

            if( data.value == 'svn' ){
               $("#id_repoUser").parent().parent().css("display","");
               $("#id_repoPassword").parent().parent().css("display","");
            }else{
                init_input()
            }
        });
    });

</script>
{% endblock %}

qcplay/apps/stark/templates/stark/changelist.html
{% extends 'layout.html' %}
{% block css %}
<style>
    .pagination {
        text-align: center;
        margin: 0 auto;
    }

    li {
        display: inline;
    }
    .ser-key{
        height: 25px;
        width: 300px;
        line-height: 50px;
    }
</style>
{% endblock %}


{% block content %}

    <div class="layui-card" style="margin: 20px">
        <div class="layui-card-header"><i class="fa fa-filter" aria-hidden="true"></i> 快速筛选</div>
        <div class="layui-card-body">
            {% if search_group_row_list %}
                <div class="search-group">
                    {% for row in search_group_row_list %}
                        <div style="margin-bottom: 5px">
                            {% for obj in row %}
                                {{ obj|safe }}
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    <div class="layui-card" style="margin: 20px">
        <div class="layui-card-header"><i class="fa fa-database" aria-hidden="true"></i> 数据
            {% if custom_btn %}   <!--同步按钮-->
                <div style="float: right;">
                    <button class="layui-btn layui-btn-sm layui-btn-danger" id="sync_host_btn">  <!--反向生成url-->
                        <i class="fa fa-refresh" aria-hidden="true"></i> 同步数据
                    </button>
                </div>
            {% endif %}
            {% if add_btn %}   <!--新增按钮-->
                <div style="float: right;margin-right: 5px;">
                    <a class="layui-btn layui-btn-sm" href="{{ add_btn|safe }}">  <!--反向生成url-->
                        <i class="fa fa-plus-square" aria-hidden="true"></i> 新增数据
                    </a>
                </div>
            {% endif %}
            {% if search_list %}  <!--搜索框-->
                <div style="float: right;">
                    <form method="get" class="layui-form" style="margin-right: 5px">
                        {% csrf_token %}
                        <input class="ser-key" type="text" name="q" value="{{ search_value }}" placeholder="关键字搜索">
                        <button class="layui-btn layui-btn-sm" type="submit">
                            <i class="fa fa-search" aria-hidden="true"> 搜索</i>
                        </button>
                    </form>
                </div>
            {% endif %}
        </div>

        <div class="layui-card-body" style="padding: 0">

            <form method="post">
                {% csrf_token %}
                {% if action_dict %}
                    <div style="float: left;margin: 5px 10px 5px 0;">
                        <div class="form-inline">
                            <div class="form-group">
                                <select class="form-control" name="action">
                                    <option value="">请选择操作</option>
                                    {% for func_name,func_text in action_dict.items %}
                                        <option value="{{ func_name }}">{{ func_text }}</option>
                                    {% endfor %}
                                </select>
                                <input class="btn btn-primary" type="submit" value="执行"/>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <table class="layui-table">
                    <thead>
                    <tr style="background-color: #00968817">
                        {% for item in header_list %}
                            <th>{{ item }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for row in body_list %}
                        <tr>
                            {% for ele in row %}
                                <td>{{ ele }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
            <nav class="pagination">
                <ul class="layui-box layui-laypage">
                    {{ pager.page_html|safe }}
                </ul>
            </nav>
            <!--{% if messages %}-->
                <!--{% for message in messages %}-->
                <!--<input id="id_msgs" type="hidden" tags="{{message.tags}}" value="{{ message }}">-->
                <!--{% endfor %}-->
            <!--{% endif %}-->
        </div>
    </div>
{% endblock %}

{% block js %}
<script>

$(function () {

    $('#sync_host_btn').click(function(){

       $.ajax({
             type: "POST",
             url: "/stark/web/idchost/sync_hosts/",
             data: {"csrfmiddlewaretoken":"{{ csrf_token }}"},
             dataType: "json",
             success: function(res){
                        if (res.status == 'success'){
                            layer.msg('同步成功', {time: 2000});
                            setTimeout(function(){
                                window.location.reload();
                            },2000)
                        }else{
                            layer.msg('同步失败', {time: 2000});
                        }

                      }
         });
    })
})

</script>

{% endblock %}

qcplay/apps/stark/templates/stark/delete.html
{% extends 'layout.html' %}

{% block content %}
  <div class="layui-row" style="margin: 20px">
    <div class="layui-col-md3">
      <div class="layui-card">
      <div class="layui-card-header">请注意 !</div>
      <div class="layui-card-body">
        <form method="post">
            {% csrf_token %}
            <p style="font-size: 16px;text-align: center;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后不可恢复，请确认是否删除</p>
            <div style="margin-top: 20px;">
                <div style="text-align: center;">
                    <a href="{{ cancel }}" class="layui-btn layui-btn-lg">取 消</a>
                    <input type="submit" class="layui-btn layui-btn-danger layui-btn-lg" value="确 认">
                </div>
            </div>
        </form>
      </div>
    </div>
    </div>
  </div>

{% endblock %}